### ISSUE TITLE
Create account is never valid

### ISSUE THREAD

**Issue by kdcrafter** [megan-crawford/BigBox#1]
Whenever correct information (e.g. John, Doe, email@email.com, etc) is manually put in the creation account form, the user is given back an empty form where the form was not valid. So no user is created.

The form will still fail even if there are no checks on the fields such as clean_email(), clean_first_name(), etc.

The create account form will work normally if `{{ form }}` is used instead of the html instead the form tag. This will result in a user being created.

Also the update account form, despite having a similar set up to the create account form, does work normally. It validates and updates the right info.

**Comment by kovacikk** [comment]
I was able to get the form to pass as Valid. The issue was that the names for the inputs were not set. Though, now it returns that there is a type error with the email field: 

<img width="544" alt="Capture" src="https://user-images.githubusercontent.com/32037559/54220771-85c5ee00-44c8-11e9-92c2-7777753b183b.PNG">

**Comment by kdcrafter** [comment]
The keyword error is gone. Just had to change the user creation to match the way we have the extended user model set up.
